// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "3532b8f8-fe41-43f9-8d08-38e16f652639";

const char SSID[]               = "mailboxwifi";    // Network SSID (name)
const char PASS[]               = "password";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "UVPK9JTUXX7OZIYOPZOO";    // Secret device password

void onLockDoorChange();
void onScheduleChange();

String door_open_status;
String door_status;
CloudSwitch lock_door;
CloudSchedule schedule;
bool schedule_active;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(door_open_status, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(door_status, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(lock_door, READWRITE, ON_CHANGE, onLockDoorChange);
  ArduinoCloud.addProperty(schedule, READWRITE, ON_CHANGE, onScheduleChange);
  ArduinoCloud.addProperty(schedule_active, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
